//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanpham
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateMember1
    {
        public int MemberID { get; set; }
        public Nullable<int> CateTinCongNghe { get; set; }
        public Nullable<int> CateMicrosoft { get; set; }
        public Nullable<int> CateSun { get; set; }
        public Nullable<int> CateCongNgheMoi { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
