//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanpham
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public News()
        {
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int NewsID { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> Posttime { get; set; }
        public string Keyword { get; set; }
        public string Image { get; set; }
        public string Link { get; set; }
        public string Status { get; set; }
        public Nullable<int> NumRead { get; set; }
        public string feedback { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
