//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanpham
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public string StatisticID { get; set; }
        public System.DateTime PostTimeNews { get; set; }
        public int PostMostRead { get; set; }
        public int VisitNumber { get; set; }
    }
}
